#
# YAML Config file for sat6cmd
#

# Application config items
application:
   prompt: "sat6cmd>"
   instpath: "./"

# Connection config items
connection:
   host: "https://rhic-satellite6.iad.salab.redhat.com"
   user: "admin"
   pass: "Redhat1234!@#$"
   verify_ssl: false
